{
  Vehicle {
    label @output @filter(op: ">=", value: ["$minLabel"])
    stop {
      stop: name @output
    }

    trip {
      route {
        long_name @output @filter(op: "!=", value: [short_name])
      }
    }
  }
}
